<div id="content-right">
			<!-- MAIN CONTENT -->
			<h1 class="center_box_heading align_left">Available Rooms</h1><div class="center_box_content"><h4 class="center_box_sub_heading"><span>From: April 30, 2017 To: May 01, 2017 (1 Night)</span></h4><br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="1">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2">
<h4><a href="index.php?page=room_description&amp;room_id=1">Single</a> <span class="green">(available)</span></h4></td></tr>
<tr><td colspan="2" height="70px">
<p>Rooms measuring 15 m² equipped with all the details expected of a superior 4 star hotel. Services: Wake up call service, Customer service, Laundry service and express laundry, Concierge service, Pillow menu.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 1</td></tr>
<tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-55">1 (55.00$)</option>
<option value="2-110">2 (110.00$)</option>
<option value="3-165">3 (165.00$)</option>
<option value="4-220">4 (220.00$)</option>
<option value="5-275">5 (275.00$)</option>
<option value="6-330">6 (330.00$)</option>
<option value="7-385">7 (385.00$)</option>
<option value="8-440">8 (440.00$)</option>
<option value="9-495">9 (495.00$)</option>
<option value="10-550">10 (550.00$)</option>
<option value="11-605">11 (605.00$)</option>
<option value="12-660">12 (660.00$)</option>
<option value="13-715">13 (715.00$)</option>
<option value="14-770">14 (770.00$)</option>
<option value="15-825">15 (825.00$)</option>
<td colspan="2"><td width="200px" align="center"><a href="images/rooms_icons/single_1.jpg" rel="lyteshow_1" title="Image 1">
<img class="room_icon" src="1.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/single_1.jpg" rel="lyteshow_1" title="Image 1"></a>  <a href="images/rooms_icons/single_2.jpg" rel="lyteshow_1" title="Image 2"></a>  <a href="images/rooms_icons/single_3.jpg" rel="lyteshow_1" title="Image 3"></a>  <a href="images/rooms_icons/single_4.jpg" rel="lyteshow_1" title="Image 4"></a>  <a href="images/rooms_icons/single_5.jpg" rel="lyteshow_1" title="Image 5"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_1" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td>  <td><span>55.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="2">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=2">Double</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Modern and functional rooms measuring approximately 20-25 m² equipped with all the details expected of the hotel. The rooms have a king or queen size bed or two single beds, in addition to beds measuring 1 by 2.2 metres ideal for sports teams.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 2</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-80">1 (80.00$)</option><option value="2-160">2 (160.00$)</option><option value="3-240">3 (240.00$)</option><option value="4-320">4 (320.00$)</option><option value="5-400">5 (400.00$)</option><option value="6-480">6 (480.00$)</option><option value="7-560">7 (560.00$)</option><option value="8-640">8 (640.00$)</option><option value="9-720">9 (720.00$)</option><option value="10-800">10 (800.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_2')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/double_1.jpg" rel="lyteshow_2" title="Image 1"><img class="room_icon" src="images/rooms_icons/double_icon_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/double_1.jpg" rel="lyteshow_2" title="Image 1"></a>  <a href="images/rooms_icons/double_2.jpg" rel="lyteshow_2" title="Image 2"></a>  <a href="images/rooms_icons/double_3.jpg" rel="lyteshow_2" title="Image 3"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_2" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td>  <td><span>80.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="3">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=3">Superior</a> <span class="red">(5 rooms left)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Spacious rooms with exquisite decor, measuring approximately 25-30 m² and equipped with all the details expected of the hotel hotel. The rooms have a king or queen size bed or two single beds, in addition to beds measuring 1 by 2.2 metres.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 3</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-140">1 (140.00$)</option><option value="2-280">2 (280.00$)</option><option value="3-420">3 (420.00$)</option><option value="4-560">4 (560.00$)</option><option value="5-700">5 (700.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_3')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/superior_1.jpg" rel="lyteshow_3" title="Image 1"><img class="room_icon" src="images/rooms_icons/superior_icon_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/superior_1.jpg" rel="lyteshow_3" title="Image 1"></a>  <a href="images/rooms_icons/superior_2.jpg" rel="lyteshow_3" title="Image 2"></a>  <a href="images/rooms_icons/superior_3.jpg" rel="lyteshow_3" title="Image 3"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_3" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="4">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=4">Luxury</a> <span class="red">(3 rooms left)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Spacious rooms with exquisite decor measuring approximately 25-30 m² and equipped with all the details expected of a superior 4 star Hotel. The rooms have a king or queen size bed or two single beds, and views of the streets.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 4</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-190">1 (190.00$)</option><option value="2-380">2 (380.00$)</option><option value="3-570">3 (570.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_4')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/luxury_1.jpg" rel="lyteshow_4" title="Image 1"><img class="room_icon" src="images/rooms_icons/luxury_icon_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/luxury_1.jpg" rel="lyteshow_4" title="Image 1"></a>  <a href="images/rooms_icons/luxury_2.jpg" rel="lyteshow_4" title="Image 2"></a>  <a href="images/rooms_icons/luxury_3.jpg" rel="lyteshow_4" title="Image 3"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_4" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td>  <td><span>190.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="5">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=5">Deluxe</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Pillowtop mattress with premium bedding. Television with premium  cable channels and pay movies. Wired Internet access (surcharge). Fax  machine and in-room safe. Complimentary newspapers. Shower/tub  combination. Bath amenities include hair dryer and complimentary  toiletries. Bathrobes. Blackout drapes/curtains, clock radio, and  electronic check-out. Air conditioning. Turndown service available on  request.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 2</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-129">1 (129.00$)</option><option value="2-258">2 (258.00$)</option><option value="3-387">3 (387.00$)</option><option value="4-516">4 (516.00$)</option><option value="5-645">5 (645.00$)</option><option value="6-774">6 (774.00$)</option><option value="7-903">7 (903.00$)</option><option value="8-1032">8 (1,032.00$)</option><option value="9-1161">9 (1,161.00$)</option><option value="10-1290">10 (1,290.00$)</option><option value="11-1419">11 (1,419.00$)</option><option value="12-1548">12 (1,548.00$)</option><option value="13-1677">13 (1,677.00$)</option><option value="14-1806">14 (1,806.00$)</option><option value="15-1935">15 (1,935.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_5')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/2_view1_lzm9xnw5s11ojzhvrosz.jpg" rel="lyteshow_5" title="Image 1"><img class="room_icon" src="images/rooms_icons/2_icon_wiztcr7x9t9iuk6l7mgc_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/2_view1_lzm9xnw5s11ojzhvrosz.jpg" rel="lyteshow_5" title="Image 1"></a>  <a href="images/rooms_icons/2_view2_m2iclnyr0e4pdpybdvf7.jpg" rel="lyteshow_5" title="Image 2"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_5" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="6">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=6">Super Deluxe</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Our rooms are inspired by a unique combination of modern and minimalist design. The Super Deluxe rooms are available with a choice of queen bed or twin beds. Each room features air-conditioning, Television, minibar/fridge, coffee/tea making facilities, personal safety box, writing desk and stationery</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 3</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-140">1 (140.00$)</option><option value="2-280">2 (280.00$)</option><option value="3-420">3 (420.00$)</option><option value="4-560">4 (560.00$)</option><option value="5-700">5 (700.00$)</option><option value="6-840">6 (840.00$)</option><option value="7-980">7 (980.00$)</option><option value="8-1120">8 (1,120.00$)</option><option value="9-1260">9 (1,260.00$)</option><option value="10-1400">10 (1,400.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_6')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/2_view1_fyo0rkvca5w82ypsqtxl.jpg" rel="lyteshow_6" title="Image 1"><img class="room_icon" src="images/rooms_icons/2_icon_xx2hqs56vgmjumkg2dpg_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/2_view1_fyo0rkvca5w82ypsqtxl.jpg" rel="lyteshow_6" title="Image 1"></a>  <a href="images/rooms_icons/2_view2_hk667pm93boa0ck2wfd8.jpg" rel="lyteshow_6" title="Image 2"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_6" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td>  <td><span>140.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="7">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=7">Respire</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Respire by Hyatt – Hypo-Allergenic Rooms are designed to provide a  comfortable sleeping environment for all guests, especially allergy  sufferers. Although all Hyatt Regency Chicago hotel rooms follow a  strict protocol for cleanliness, Respire by Hyatt rooms undergo an  additional six-step process to reduce airborne particles and minimize  the presence of potential irritants.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 2</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-88">1 (88.00$)</option><option value="2-176">2 (176.00$)</option><option value="3-264">3 (264.00$)</option><option value="4-352">4 (352.00$)</option><option value="5-440">5 (440.00$)</option><option value="6-528">6 (528.00$)</option><option value="7-616">7 (616.00$)</option><option value="8-704">8 (704.00$)</option><option value="9-792">9 (792.00$)</option><option value="10-880">10 (880.00$)</option><option value="11-968">11 (968.00$)</option><option value="12-1056">12 (1,056.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_7')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/3_view1_sdkpabusey0lcjr3vk9d.jpg" rel="lyteshow_7" title="Image 1"><img class="room_icon" src="images/rooms_icons/3_icon_fda6qbs6hphwjddr3fdu_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/3_view1_sdkpabusey0lcjr3vk9d.jpg" rel="lyteshow_7" title="Image 1"></a>  <a href="images/rooms_icons/3_view2_hq0t4mk73y1rblglwbea.jpg" rel="lyteshow_7" title="Image 2"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_7" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td>  <td><span>88.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="8">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=8">Two-Bedroom Suite</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Our two bedroom Executive Suite offers luxury and space with two  separate bedrooms and living room, furnished with everything you require  for business or leisure</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 2</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-129">1 (129.00$)</option><option value="2-258">2 (258.00$)</option><option value="3-387">3 (387.00$)</option><option value="4-516">4 (516.00$)</option><option value="5-645">5 (645.00$)</option><option value="6-774">6 (774.00$)</option><option value="7-903">7 (903.00$)</option><option value="8-1032">8 (1,032.00$)</option><option value="9-1161">9 (1,161.00$)</option><option value="10-1290">10 (1,290.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_8')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/4_view1_qv2naw04qary1qz0tkbd.jpg" rel="lyteshow_8" title="Image 1"><img class="room_icon" src="images/rooms_icons/4_icon_gqy193l2kjmiodx20fk7_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/4_view1_qv2naw04qary1qz0tkbd.jpg" rel="lyteshow_8" title="Image 1"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_8" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td>  <td><span>129.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><div class="line-hor"></div></td></tr></tbody></table>
</form>
<br><form action="index.php?page=booking" method="post">
<input type="hidden" name="room_id" value="9">
<input type="hidden" name="from_date" value="2017-04-30">
<input type="hidden" name="to_date" value="2017-05-01">
<input type="hidden" name="nights" value="1">
<input type="hidden" name="adults" value="1">
<input type="hidden" name="children" value="">
<input type="hidden" name="checkin_year_month" value="2017-4">
<input type="hidden" name="checkin_monthday" value="30">
<input type="hidden" name="checkout_year_month" value="2017-5">
<input type="hidden" name="checkout_monthday" value="01">
<input type="hidden" name="token" value="7d38768fb4fd0e4ee037cb725dd5e63c">
<table border="0">
<tbody><tr valign="top"><td><table border="0" width="420px"><tbody><tr><td colspan="2"><h4><a href="index.php?page=room_description&amp;room_id=9">Double Room</a> <span class="green">(available)</span></h4></td></tr><tr><td colspan="2" height="70px"><p>Richly appointed, Deluxe Guest Rooms feature traditional decor.  Upscale amenities, services, and furnishings provide the comforts of  home with the convenience of the office. Amenities include high-speed  wired and wireless internet access, two-line speaker phones with  voicemail.</p></td></tr><tr><td colspan="2" nowrap="nowrap" height="5px"></td></tr><tr><td colspan="2">Max Adults: 3</td></tr><tr><td>Rooms:</td><td><select name="available_rooms" class="available_rooms_ddl"><option value="1-144">1 (144.00$)</option><option value="2-288">2 (288.00$)</option><option value="3-432">3 (432.00$)</option><option value="4-576">4 (576.00$)</option><option value="5-720">5 (720.00$)</option><option value="6-864">6 (864.00$)</option><option value="7-1008">7 (1,008.00$)</option><option value="8-1152">8 (1,152.00$)</option><option value="9-1296">9 (1,296.00$)</option></select></td></tr><tr><td>Meal Plans:</td><td>
														<select name="meal_plans" class="available_rooms_ddl"><option value="1">Breakfast (Included) 0.00$</option><option value="7">Breakfast 7.00$</option><option value="2">Half Board 10.00$</option><option value="3">Full Board 22.00$</option><option value="5">Breakfast  11.00$</option><option value="6">Breakfast 12.00$</option></select>
													</td></tr><tr><td></td><td>Person/Per Night</td></tr><tr><td colspan="2"><a class="price_link" href="javascript:void(0);" onclick="javascript:appToggleElement('row_prices_9')" title="Click to see prices">Prices (+)</a></td></tr></tbody></table></td><td width="200px" align="center"><a href="images/rooms_icons/5_view1_sqhfh1m3et05w6e1huek.jpg" rel="lyteshow_9" title="Image 1"><img class="room_icon" src="images/rooms_icons/5_icon_s3va5cfd416tjrkhy24m_thumb.jpg" width="165px" alt="icon"></a>  <a href="images/rooms_icons/5_view1_sqhfh1m3et05w6e1huek.jpg" rel="lyteshow_9" title="Image 1"></a><input type="submit" class="form_button_middle" style="margin-top:10px;" value="Book Now!"></td></tr><tr><td colspan="2"><span id="row_prices_9" style="margin:5px 5px 10px 5px;display:none;"><table class="room_prices" border="0" cellpadding="0" cellspacing="0"><tbody><tr class="header">  <th width="5px">&nbsp;  </th><th colspan="3" width="145px">&nbsp;  </th><th width="10px">&nbsp;  </th><th>Mon  </th><th>Tue  </th><th>Wed  </th><th>Thu  </th><th>Fri  </th><th>Sat  </th><th>Sun</th></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr><tr align="center">  <td></td>  <td align="left" nowrap="nowrap" colspan="3"><b>Standard Price</b></td>  <td></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td>  <td><span>144.00$</span></td></tr><tr><td colspan="12" nowrap="nowrap" height="5px"></td></tr></tbody></table></span></td></tr><tr><td colspan="2"><br></td></tr></tbody></table>
</form>
</div>			<!-- END OF MAIN CONTENT -->			
		</div>